/* libspire_misc.h generated by valac 0.12.0, the Vala compiler, do not modify */


#ifndef __R__OPERADORES_EDWINDLC_PROGRAMACION_PROYECTOSSOFTWARE_SOFTWARE_VALA_PROYECTOSVALA_PROYECTS_LIBSPIRE_MISC_BIN_WIN_LIBSPIRE_MISC_H__
#define __R__OPERADORES_EDWINDLC_PROGRAMACION_PROYECTOSSOFTWARE_SOFTWARE_VALA_PROYECTOSVALA_PROYECTS_LIBSPIRE_MISC_BIN_WIN_LIBSPIRE_MISC_H__

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS


#define EDWINSPIRE_MISC_TYPE_CRYPTO_SPIRE (edwinspire_misc_crypto_spire_get_type ())
#define EDWINSPIRE_MISC_CRYPTO_SPIRE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EDWINSPIRE_MISC_TYPE_CRYPTO_SPIRE, edwinspireMiscCryptoSpire))
#define EDWINSPIRE_MISC_CRYPTO_SPIRE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EDWINSPIRE_MISC_TYPE_CRYPTO_SPIRE, edwinspireMiscCryptoSpireClass))
#define EDWINSPIRE_MISC_IS_CRYPTO_SPIRE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EDWINSPIRE_MISC_TYPE_CRYPTO_SPIRE))
#define EDWINSPIRE_MISC_IS_CRYPTO_SPIRE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EDWINSPIRE_MISC_TYPE_CRYPTO_SPIRE))
#define EDWINSPIRE_MISC_CRYPTO_SPIRE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EDWINSPIRE_MISC_TYPE_CRYPTO_SPIRE, edwinspireMiscCryptoSpireClass))

typedef struct _edwinspireMiscCryptoSpire edwinspireMiscCryptoSpire;
typedef struct _edwinspireMiscCryptoSpireClass edwinspireMiscCryptoSpireClass;
typedef struct _edwinspireMiscCryptoSpirePrivate edwinspireMiscCryptoSpirePrivate;

#define EDWINSPIRE_MISC_TYPE_MISCELLANEOUS (edwinspire_misc_miscellaneous_get_type ())
#define EDWINSPIRE_MISC_MISCELLANEOUS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EDWINSPIRE_MISC_TYPE_MISCELLANEOUS, edwinspireMiscMiscellaneous))
#define EDWINSPIRE_MISC_MISCELLANEOUS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EDWINSPIRE_MISC_TYPE_MISCELLANEOUS, edwinspireMiscMiscellaneousClass))
#define EDWINSPIRE_MISC_IS_MISCELLANEOUS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EDWINSPIRE_MISC_TYPE_MISCELLANEOUS))
#define EDWINSPIRE_MISC_IS_MISCELLANEOUS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EDWINSPIRE_MISC_TYPE_MISCELLANEOUS))
#define EDWINSPIRE_MISC_MISCELLANEOUS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EDWINSPIRE_MISC_TYPE_MISCELLANEOUS, edwinspireMiscMiscellaneousClass))

typedef struct _edwinspireMiscMiscellaneous edwinspireMiscMiscellaneous;
typedef struct _edwinspireMiscMiscellaneousClass edwinspireMiscMiscellaneousClass;
typedef struct _edwinspireMiscMiscellaneousPrivate edwinspireMiscMiscellaneousPrivate;

struct _edwinspireMiscCryptoSpire {
	GObject parent_instance;
	edwinspireMiscCryptoSpirePrivate * priv;
};

struct _edwinspireMiscCryptoSpireClass {
	GObjectClass parent_class;
};

struct _edwinspireMiscMiscellaneous {
	GObject parent_instance;
	edwinspireMiscMiscellaneousPrivate * priv;
};

struct _edwinspireMiscMiscellaneousClass {
	GObjectClass parent_class;
};


GType edwinspire_misc_crypto_spire_get_type (void) G_GNUC_CONST;
edwinspireMiscCryptoSpire* edwinspire_misc_crypto_spire_new (void);
edwinspireMiscCryptoSpire* edwinspire_misc_crypto_spire_construct (GType object_type);
gchar* edwinspire_misc_crypto_spire_ENCry (const gchar* Key, const gchar* Word);
gchar* edwinspire_misc_crypto_spire_DECry (const gchar* Key, const gchar* Word);
GType edwinspire_misc_miscellaneous_get_type (void) G_GNUC_CONST;
gchar* edwinspire_misc_miscellaneous_StringTrim (const gchar* value);
GDateTime* edwinspire_misc_miscellaneous_DateTimeFromStringISO8601 (const gchar* iso8601format);
gint edwinspire_misc_miscellaneous_hex2number (const gchar* buffer);
gint edwinspire_misc_miscellaneous_ConvertBinToInt (const gchar* Binary);
gchar* edwinspire_misc_miscellaneous_ConvertIntToBin (gint Number, gint Length);
gboolean edwinspire_misc_miscellaneous_IsPair (gint Num);
gchar* edwinspire_misc_miscellaneous_number2hex (gint Decimal, guint Digits);
gchar* edwinspire_misc_miscellaneous_PathRun (void);
gchar* edwinspire_misc_miscellaneous_getMd5Hash (const gchar* InputString);
gboolean edwinspire_misc_miscellaneous_verifyMd5Hash (const gchar* input, const gchar* hash);
edwinspireMiscMiscellaneous* edwinspire_misc_miscellaneous_new (void);
edwinspireMiscMiscellaneous* edwinspire_misc_miscellaneous_construct (GType object_type);


G_END_DECLS

#endif
