/* libspire_mysql.h generated by valac 0.12.0, the Vala compiler, do not modify */


#ifndef __R__OPERADORES_EDWINDLC_PROGRAMACION_PROYECTOSSOFTWARE_SOFTWARE_VALA_PROYECTOSVALA_PROYECTS_LIBSPIRE_MYSQL_BIN_WIN_LIBSPIRE_MYSQL_H__
#define __R__OPERADORES_EDWINDLC_PROGRAMACION_PROYECTOSSOFTWARE_SOFTWARE_VALA_PROYECTOSVALA_PROYECTS_LIBSPIRE_MYSQL_BIN_WIN_LIBSPIRE_MYSQL_H__

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <gee.h>

G_BEGIN_DECLS


#define EDWINSPIRE_LIB_MY_SQL_TYPE_QUERY_BUILDER (edwinspire_lib_my_sql_query_builder_get_type ())
#define EDWINSPIRE_LIB_MY_SQL_QUERY_BUILDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EDWINSPIRE_LIB_MY_SQL_TYPE_QUERY_BUILDER, edwinspireLibMySQLQueryBuilder))
#define EDWINSPIRE_LIB_MY_SQL_QUERY_BUILDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EDWINSPIRE_LIB_MY_SQL_TYPE_QUERY_BUILDER, edwinspireLibMySQLQueryBuilderClass))
#define EDWINSPIRE_LIB_MY_SQL_IS_QUERY_BUILDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EDWINSPIRE_LIB_MY_SQL_TYPE_QUERY_BUILDER))
#define EDWINSPIRE_LIB_MY_SQL_IS_QUERY_BUILDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EDWINSPIRE_LIB_MY_SQL_TYPE_QUERY_BUILDER))
#define EDWINSPIRE_LIB_MY_SQL_QUERY_BUILDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EDWINSPIRE_LIB_MY_SQL_TYPE_QUERY_BUILDER, edwinspireLibMySQLQueryBuilderClass))

typedef struct _edwinspireLibMySQLQueryBuilder edwinspireLibMySQLQueryBuilder;
typedef struct _edwinspireLibMySQLQueryBuilderClass edwinspireLibMySQLQueryBuilderClass;
typedef struct _edwinspireLibMySQLQueryBuilderPrivate edwinspireLibMySQLQueryBuilderPrivate;

#define EDWINSPIRE_LIB_MY_SQL_TYPE_MY_SQL (edwinspire_lib_my_sql_my_sql_get_type ())
#define EDWINSPIRE_LIB_MY_SQL_MY_SQL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EDWINSPIRE_LIB_MY_SQL_TYPE_MY_SQL, edwinspireLibMySQLMySQL))
#define EDWINSPIRE_LIB_MY_SQL_MY_SQL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EDWINSPIRE_LIB_MY_SQL_TYPE_MY_SQL, edwinspireLibMySQLMySQLClass))
#define EDWINSPIRE_LIB_MY_SQL_IS_MY_SQL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EDWINSPIRE_LIB_MY_SQL_TYPE_MY_SQL))
#define EDWINSPIRE_LIB_MY_SQL_IS_MY_SQL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EDWINSPIRE_LIB_MY_SQL_TYPE_MY_SQL))
#define EDWINSPIRE_LIB_MY_SQL_MY_SQL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EDWINSPIRE_LIB_MY_SQL_TYPE_MY_SQL, edwinspireLibMySQLMySQLClass))

typedef struct _edwinspireLibMySQLMySQL edwinspireLibMySQLMySQL;
typedef struct _edwinspireLibMySQLMySQLClass edwinspireLibMySQLMySQLClass;
typedef struct _edwinspireLibMySQLMySQLPrivate edwinspireLibMySQLMySQLPrivate;

struct _edwinspireLibMySQLQueryBuilder {
	GObject parent_instance;
	edwinspireLibMySQLQueryBuilderPrivate * priv;
};

struct _edwinspireLibMySQLQueryBuilderClass {
	GObjectClass parent_class;
};

struct _edwinspireLibMySQLMySQL {
	GObject parent_instance;
	edwinspireLibMySQLMySQLPrivate * priv;
	gchar* Host;
	gchar* Uid;
	gchar* Password;
	gchar* DataBase;
	guint Port;
};

struct _edwinspireLibMySQLMySQLClass {
	GObjectClass parent_class;
};


GType edwinspire_lib_my_sql_query_builder_get_type (void) G_GNUC_CONST;
edwinspireLibMySQLQueryBuilder* edwinspire_lib_my_sql_query_builder_new_expr (const gchar* Expr);
edwinspireLibMySQLQueryBuilder* edwinspire_lib_my_sql_query_builder_construct_expr (GType object_type, const gchar* Expr);
edwinspireLibMySQLQueryBuilder* edwinspire_lib_my_sql_query_builder_new (void);
edwinspireLibMySQLQueryBuilder* edwinspire_lib_my_sql_query_builder_construct (GType object_type);
void edwinspire_lib_my_sql_query_builder_clear (edwinspireLibMySQLQueryBuilder* self);
void edwinspire_lib_my_sql_query_builder_set_int (edwinspireLibMySQLQueryBuilder* self, const gchar* Name, gint value_);
gint edwinspire_lib_my_sql_query_builder_get_int (edwinspireLibMySQLQueryBuilder* self, const gchar* Name_);
void edwinspire_lib_my_sql_query_builder_set_uint (edwinspireLibMySQLQueryBuilder* self, const gchar* Name, guint value_);
void edwinspire_lib_my_sql_query_builder_set_string (edwinspireLibMySQLQueryBuilder* self, const gchar* Name, const gchar* value_);
gchar* edwinspire_lib_my_sql_query_builder_get_string (edwinspireLibMySQLQueryBuilder* self, const gchar* Name_);
void edwinspire_lib_my_sql_query_builder_set_mysql_function (edwinspireLibMySQLQueryBuilder* self, const gchar* Name, const gchar* function_name);
gchar* edwinspire_lib_my_sql_query_builder_get_mysql_function (edwinspireLibMySQLQueryBuilder* self, const gchar* Name_);
void edwinspire_lib_my_sql_query_builder_set_bool (edwinspireLibMySQLQueryBuilder* self, const gchar* Name, gboolean value_);
gboolean edwinspire_lib_my_sql_query_builder_get_bool (edwinspireLibMySQLQueryBuilder* self, const gchar* Name_);
void edwinspire_lib_my_sql_query_builder_set_DateTime (edwinspireLibMySQLQueryBuilder* self, const gchar* Name, GDateTime* value_);
GDateTime* edwinspire_lib_my_sql_query_builder_get_DateTime (edwinspireLibMySQLQueryBuilder* self, const gchar* Name_);
void edwinspire_lib_my_sql_query_builder_set_long (edwinspireLibMySQLQueryBuilder* self, const gchar* Name, glong value_);
glong edwinspire_lib_my_sql_query_builder_get_long (edwinspireLibMySQLQueryBuilder* self, const gchar* Name_);
void edwinspire_lib_my_sql_query_builder_set_ulong (edwinspireLibMySQLQueryBuilder* self, const gchar* Name, gulong value_);
gulong edwinspire_lib_my_sql_query_builder_get_ulong (edwinspireLibMySQLQueryBuilder* self, const gchar* Name_);
void edwinspire_lib_my_sql_query_builder_set_float (edwinspireLibMySQLQueryBuilder* self, const gchar* Name, gfloat value_);
gfloat edwinspire_lib_my_sql_query_builder_get_float (edwinspireLibMySQLQueryBuilder* self, const gchar* Name_);
void edwinspire_lib_my_sql_query_builder_set_double (edwinspireLibMySQLQueryBuilder* self, const gchar* Name, gdouble value_);
gdouble edwinspire_lib_my_sql_query_builder_get_double (edwinspireLibMySQLQueryBuilder* self, const gchar* Name_);
gchar* edwinspire_lib_my_sql_query_builder_query (edwinspireLibMySQLQueryBuilder* self);
const gchar* edwinspire_lib_my_sql_query_builder_get_Exp (edwinspireLibMySQLQueryBuilder* self);
void edwinspire_lib_my_sql_query_builder_set_Exp (edwinspireLibMySQLQueryBuilder* self, const gchar* value);
GType edwinspire_lib_my_sql_my_sql_get_type (void) G_GNUC_CONST;
edwinspireLibMySQLMySQL* edwinspire_lib_my_sql_my_sql_new (void);
edwinspireLibMySQLMySQL* edwinspire_lib_my_sql_my_sql_construct (GType object_type);
GeeArrayList* edwinspire_lib_my_sql_my_sql_ExecuteReaderNameFields (edwinspireLibMySQLMySQL* self, const gchar* Query, const gchar* Table);
GeeArrayList* edwinspire_lib_my_sql_my_sql_ExecuteReaderNumFields (edwinspireLibMySQLMySQL* self, const gchar* Query);
void edwinspire_lib_my_sql_my_sql_Close (edwinspireLibMySQLMySQL* self);
gboolean edwinspire_lib_my_sql_my_sql_Open (edwinspireLibMySQLMySQL* self);
gchar* edwinspire_lib_my_sql_my_sql_ServerInfo (edwinspireLibMySQLMySQL* self);
gboolean edwinspire_lib_my_sql_my_sql_QuerySend (edwinspireLibMySQLMySQL* self, const gchar* Query);
GeeHashMap* edwinspire_lib_my_sql_my_sql_StoreProcedure (edwinspireLibMySQLMySQL* self, const gchar* Query);
gulong edwinspire_lib_my_sql_my_sql_INSERT_REPLACE (edwinspireLibMySQLMySQL* self, const gchar* Query);
gulong edwinspire_lib_my_sql_my_sql_ExecuteNonQuery_Affected_Rows (edwinspireLibMySQLMySQL* self, const gchar* Query);
gboolean edwinspire_lib_my_sql_my_sql_ExecuteNonQuery (edwinspireLibMySQLMySQL* self, const gchar* Query);
gint edwinspire_lib_my_sql_my_sql_GetInt (edwinspireLibMySQLMySQL* self, GeeHashMap* Rowx, guint Field);
gboolean edwinspire_lib_my_sql_my_sql_get_IsOpen (edwinspireLibMySQLMySQL* self);


G_END_DECLS

#endif
