/* libspire_uwebserver.h generated by valac 0.12.0, the Vala compiler, do not modify */


#ifndef __F__PROYECTOSVALA_PROYECTS_LIBSPIRE_UWEBSERVER_BIN_WIN_LIBSPIRE_UWEBSERVER_H__
#define __F__PROYECTOSVALA_PROYECTS_LIBSPIRE_UWEBSERVER_BIN_WIN_LIBSPIRE_UWEBSERVER_H__

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS


#define EDWINSPIRE_WEB_SERVER_TYPE_SERVER (edwinspire_web_server_server_get_type ())
#define EDWINSPIRE_WEB_SERVER_SERVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EDWINSPIRE_WEB_SERVER_TYPE_SERVER, edwinspireWebServerServer))
#define EDWINSPIRE_WEB_SERVER_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EDWINSPIRE_WEB_SERVER_TYPE_SERVER, edwinspireWebServerServerClass))
#define EDWINSPIRE_WEB_SERVER_IS_SERVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EDWINSPIRE_WEB_SERVER_TYPE_SERVER))
#define EDWINSPIRE_WEB_SERVER_IS_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EDWINSPIRE_WEB_SERVER_TYPE_SERVER))
#define EDWINSPIRE_WEB_SERVER_SERVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EDWINSPIRE_WEB_SERVER_TYPE_SERVER, edwinspireWebServerServerClass))

typedef struct _edwinspireWebServerServer edwinspireWebServerServer;
typedef struct _edwinspireWebServerServerClass edwinspireWebServerServerClass;
typedef struct _edwinspireWebServerServerPrivate edwinspireWebServerServerPrivate;

struct _edwinspireWebServerServer {
	GObject parent_instance;
	edwinspireWebServerServerPrivate * priv;
	guint16 Socket;
};

struct _edwinspireWebServerServerClass {
	GObjectClass parent_class;
	guint8* (*Proccess) (edwinspireWebServerServer* self, const gchar* Request, int* result_length1);
};


GType edwinspire_web_server_server_get_type (void) G_GNUC_CONST;
edwinspireWebServerServer* edwinspire_web_server_server_construct (GType object_type);
void edwinspire_web_server_server_Start (edwinspireWebServerServer* self);
guint8* edwinspire_web_server_server_Proccess (edwinspireWebServerServer* self, const gchar* Request, int* result_length1);


G_END_DECLS

#endif
