/* libspire_utilities.h generated by valac 0.20.1, the Vala compiler, do not modify */


#ifndef __E__PROYECTS_LIBSPIRE_UTILITIES_BIN_WIN_LIBSPIRE_UTILITIES_H__
#define __E__PROYECTS_LIBSPIRE_UTILITIES_BIN_WIN_LIBSPIRE_UTILITIES_H__

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <gee.h>

G_BEGIN_DECLS


#define EDWINSPIRE_UTILS_TYPE_FILE_FUNCTIONS (edwinspire_utils_file_functions_get_type ())
#define EDWINSPIRE_UTILS_FILE_FUNCTIONS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EDWINSPIRE_UTILS_TYPE_FILE_FUNCTIONS, edwinspireutilsFileFunctions))
#define EDWINSPIRE_UTILS_FILE_FUNCTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EDWINSPIRE_UTILS_TYPE_FILE_FUNCTIONS, edwinspireutilsFileFunctionsClass))
#define EDWINSPIRE_UTILS_IS_FILE_FUNCTIONS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EDWINSPIRE_UTILS_TYPE_FILE_FUNCTIONS))
#define EDWINSPIRE_UTILS_IS_FILE_FUNCTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EDWINSPIRE_UTILS_TYPE_FILE_FUNCTIONS))
#define EDWINSPIRE_UTILS_FILE_FUNCTIONS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EDWINSPIRE_UTILS_TYPE_FILE_FUNCTIONS, edwinspireutilsFileFunctionsClass))

typedef struct _edwinspireutilsFileFunctions edwinspireutilsFileFunctions;
typedef struct _edwinspireutilsFileFunctionsClass edwinspireutilsFileFunctionsClass;
typedef struct _edwinspireutilsFileFunctionsPrivate edwinspireutilsFileFunctionsPrivate;

#define EDWINSPIRE_UTILS_TYPE_BINARY_DATA (edwinspire_utils_binary_data_get_type ())
#define EDWINSPIRE_UTILS_BINARY_DATA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EDWINSPIRE_UTILS_TYPE_BINARY_DATA, edwinspireutilsBinaryData))
#define EDWINSPIRE_UTILS_BINARY_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EDWINSPIRE_UTILS_TYPE_BINARY_DATA, edwinspireutilsBinaryDataClass))
#define EDWINSPIRE_UTILS_IS_BINARY_DATA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EDWINSPIRE_UTILS_TYPE_BINARY_DATA))
#define EDWINSPIRE_UTILS_IS_BINARY_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EDWINSPIRE_UTILS_TYPE_BINARY_DATA))
#define EDWINSPIRE_UTILS_BINARY_DATA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EDWINSPIRE_UTILS_TYPE_BINARY_DATA, edwinspireutilsBinaryDataClass))

typedef struct _edwinspireutilsBinaryData edwinspireutilsBinaryData;
typedef struct _edwinspireutilsBinaryDataClass edwinspireutilsBinaryDataClass;

#define EDWINSPIRE_UTILS_TYPE_KEY_VALUE_FILE (edwinspire_utils_key_value_file_get_type ())
#define EDWINSPIRE_UTILS_KEY_VALUE_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EDWINSPIRE_UTILS_TYPE_KEY_VALUE_FILE, edwinspireutilsKeyValueFile))
#define EDWINSPIRE_UTILS_KEY_VALUE_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EDWINSPIRE_UTILS_TYPE_KEY_VALUE_FILE, edwinspireutilsKeyValueFileClass))
#define EDWINSPIRE_UTILS_IS_KEY_VALUE_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EDWINSPIRE_UTILS_TYPE_KEY_VALUE_FILE))
#define EDWINSPIRE_UTILS_IS_KEY_VALUE_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EDWINSPIRE_UTILS_TYPE_KEY_VALUE_FILE))
#define EDWINSPIRE_UTILS_KEY_VALUE_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EDWINSPIRE_UTILS_TYPE_KEY_VALUE_FILE, edwinspireutilsKeyValueFileClass))

typedef struct _edwinspireutilsKeyValueFile edwinspireutilsKeyValueFile;
typedef struct _edwinspireutilsKeyValueFileClass edwinspireutilsKeyValueFileClass;
typedef struct _edwinspireutilsKeyValueFilePrivate edwinspireutilsKeyValueFilePrivate;

#define EDWINSPIRE_UTILS_TYPE_FILES_LINES_ARRAY (edwinspire_utils_files_lines_array_get_type ())
#define EDWINSPIRE_UTILS_FILES_LINES_ARRAY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EDWINSPIRE_UTILS_TYPE_FILES_LINES_ARRAY, edwinspireutilsFilesLinesArray))
#define EDWINSPIRE_UTILS_FILES_LINES_ARRAY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EDWINSPIRE_UTILS_TYPE_FILES_LINES_ARRAY, edwinspireutilsFilesLinesArrayClass))
#define EDWINSPIRE_UTILS_IS_FILES_LINES_ARRAY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EDWINSPIRE_UTILS_TYPE_FILES_LINES_ARRAY))
#define EDWINSPIRE_UTILS_IS_FILES_LINES_ARRAY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EDWINSPIRE_UTILS_TYPE_FILES_LINES_ARRAY))
#define EDWINSPIRE_UTILS_FILES_LINES_ARRAY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EDWINSPIRE_UTILS_TYPE_FILES_LINES_ARRAY, edwinspireutilsFilesLinesArrayClass))

typedef struct _edwinspireutilsFilesLinesArray edwinspireutilsFilesLinesArray;
typedef struct _edwinspireutilsFilesLinesArrayClass edwinspireutilsFilesLinesArrayClass;
typedef struct _edwinspireutilsFilesLinesArrayPrivate edwinspireutilsFilesLinesArrayPrivate;
typedef struct _edwinspireutilsBinaryDataPrivate edwinspireutilsBinaryDataPrivate;

struct _edwinspireutilsFileFunctions {
	GObject parent_instance;
	edwinspireutilsFileFunctionsPrivate * priv;
	gchar* file_name;
};

struct _edwinspireutilsFileFunctionsClass {
	GObjectClass parent_class;
};

struct _edwinspireutilsKeyValueFile {
	edwinspireutilsFileFunctions parent_instance;
	edwinspireutilsKeyValueFilePrivate * priv;
	gchar* Exp;
	gchar* default_message;
	GeeHashMap* KeyValue;
};

struct _edwinspireutilsKeyValueFileClass {
	edwinspireutilsFileFunctionsClass parent_class;
};

struct _edwinspireutilsFilesLinesArray {
	edwinspireutilsFileFunctions parent_instance;
	edwinspireutilsFilesLinesArrayPrivate * priv;
	GeeArrayList* Lines;
	gchar* default_message;
};

struct _edwinspireutilsFilesLinesArrayClass {
	edwinspireutilsFileFunctionsClass parent_class;
};

struct _edwinspireutilsBinaryData {
	GObject parent_instance;
	edwinspireutilsBinaryDataPrivate * priv;
};

struct _edwinspireutilsBinaryDataClass {
	GObjectClass parent_class;
};


GType edwinspire_utils_file_functions_get_type (void) G_GNUC_CONST;
edwinspireutilsFileFunctions* edwinspire_utils_file_functions_new (void);
edwinspireutilsFileFunctions* edwinspire_utils_file_functions_construct (GType object_type);
GDataInputStream* edwinspire_utils_file_functions_create_DataInputStream_from_data (guint8* data, int data_length1);
gchar* edwinspire_utils_file_functions_text_strip (const gchar* t);
glong edwinspire_utils_file_functions_create_new_file (edwinspireutilsFileFunctions* self, guint8* data, int data_length1);
glong edwinspire_utils_file_functions_save_file (const gchar* full_path, guint8* data, int data_length1, gboolean replace);
glong edwinspire_utils_file_functions_write_file (edwinspireutilsFileFunctions* self, guint8* data, int data_length1, gboolean replace);
guint8* edwinspire_utils_file_functions_read_file (edwinspireutilsFileFunctions* self, int* result_length1);
GType edwinspire_utils_binary_data_get_type (void) G_GNUC_CONST;
edwinspireutilsBinaryData* edwinspire_utils_file_functions_read_as_binarydata (edwinspireutilsFileFunctions* self);
gchar* edwinspire_utils_file_functions_load_only_valid_unichars (edwinspireutilsFileFunctions* self);
const gchar* edwinspire_utils_file_functions_get_full_path (edwinspireutilsFileFunctions* self);
GType edwinspire_utils_key_value_file_get_type (void) G_GNUC_CONST;
edwinspireutilsKeyValueFile* edwinspire_utils_key_value_file_new (void);
edwinspireutilsKeyValueFile* edwinspire_utils_key_value_file_construct (GType object_type);
gchar* edwinspire_utils_key_value_file_HashMapToString (GeeHashMap* hm);
gchar* edwinspire_utils_key_value_file_to_string (edwinspireutilsKeyValueFile* self, const gchar* title);
void edwinspire_utils_key_value_file_load (edwinspireutilsKeyValueFile* self);
gchar* edwinspire_utils_key_value_file_get_as_string (edwinspireutilsKeyValueFile* self, const gchar* key);
gboolean edwinspire_utils_key_value_file_get_as_bool (edwinspireutilsKeyValueFile* self, const gchar* key);
guint16 edwinspire_utils_key_value_file_get_as_uint16 (edwinspireutilsKeyValueFile* self, const gchar* key);
gint edwinspire_utils_key_value_file_get_as_int (edwinspireutilsKeyValueFile* self, const gchar* key);
GType edwinspire_utils_files_lines_array_get_type (void) G_GNUC_CONST;
edwinspireutilsFilesLinesArray* edwinspire_utils_files_lines_array_new (void);
edwinspireutilsFilesLinesArray* edwinspire_utils_files_lines_array_construct (GType object_type);
void edwinspire_utils_files_lines_array_load (edwinspireutilsFilesLinesArray* self);
edwinspireutilsBinaryData* edwinspire_utils_binary_data_new (guint8* binary, int binary_length1);
edwinspireutilsBinaryData* edwinspire_utils_binary_data_construct (GType object_type, guint8* binary, int binary_length1);
gchar* edwinspire_utils_binary_data_md5 (edwinspireutilsBinaryData* self);
gchar* edwinspire_utils_binary_data_to_string (edwinspireutilsBinaryData* self);
void edwinspire_utils_binary_data_add_uint8 (edwinspireutilsBinaryData* self, guint8 byte);
gchar* edwinspire_utils_binary_data_to_string_only_valid_unichars (edwinspireutilsBinaryData* self);
gint edwinspire_utils_binary_data_get_length (edwinspireutilsBinaryData* self);
guint8* edwinspire_utils_binary_data_get_data (edwinspireutilsBinaryData* self, int* result_length1);
void edwinspire_utils_binary_data_set_data (edwinspireutilsBinaryData* self, guint8* value, int value_length1);


G_END_DECLS

#endif
